// Add Routes contants here
export const ROOT = '/';
export const SIGNUP = '/auth/signup';
export const LOGIN = '/auth/login';
export const ACTIVATE_ACCOUNT = '/auth/activate-account';
export const FORGOT_PASSWORD = '/auth/forgot-password';
export const RESET_PASSWORD = '/auth/reset-password';
export const ALL_PRODUCTS = '/all-products';
export const PAGE_NOT_FOUND = '*';
